### PR TITLE
WaitInteractive and MustWaitInteractive function

### PR DESCRIPTION
**Pull request by Pradakicks**
Added WaitInteractive and MustWaitInteractive function. Waits till "document.readyState == "interactive"" or if page is already loaded it will return.

Reason for a new feature - https://github.com/go-rod/rod/issues/494

Please review the code. Check if implemented correctly . First time contributing to an open-source. If there is anything I missed please let me know so I can improve.

### CODE REVIEW

**Comment by Pradakicks** [comment]
Ok just added this example

**Comment by ysmood** [comment]
Please read the CI error and fix them.

**Comment by Pradakicks** [comment]
How is the helper.go file generated(lib/js/helper.go)

**Comment by ysmood** [comment]
Read the comment of the `helper.go` file

**Comment by Pradakicks** [comment]
Ok All should be good

**Comment by ysmood** [comment]
I renamed the master branch to main, the master branch doesn't exist anymore, Github will auto close PR for non-exist branch.

Sorry for the inconvenient, could you please remake a PR and link it to this old one?

**Pull request closed without merging**
