### PR TITLE
Few minor fixes

### PR DESCRIPTION
**Pull request by egonelbre**
Made few tiny improvements. Feel free to ignore the changes that you don't care about.

_Each commit in the PR is independently reviewable._

### CODE REVIEW

**Comment by ysmood** [comment]
I sent you an invitation to https://github.com/go-rod, it will be great if you can accept it.

**Comment by egonelbre** [comment]
I added a separate test for the launch failure, however, I'm not quite sure how to integrate it with got testsuite.

Similarly, it required modifying globals to force a launcher failure... if there's a better way to make it fail, let me know.

**Comment by egonelbre** [comment]
Seems adding it as part of `got` testsuite doesn't work, it caused a really bizarre error https://github.com/go-rod/rod/runs/2710340092. It seems to work locally though.

**Comment by ysmood** [comment]
> Seems adding it as part of `got` testsuite doesn't work, it caused a really bizarre error https://github.com/go-rod/rod/runs/2710340092. It seems to work locally though.

It's just because Github Actions is not stable enough, sometimes they have a heavy load and hang forever. Just rerun the workflow will do.

**Review by ysmood — APPROVED** [review]
👍🏼

**Pull request merged**
