### PR TITLE
Add ability to capture screencast frame and convert it to AVI movie

### PR DESCRIPTION
**Pull request by muhibbudins**
This PR aims to resolve issue #22 regarding the ability to record processes on a running page, this function is like using the `Screenshot` function but with two additional functions as a trigger.

Example usage

```go
func main() {
	browser := rod.New().MustConnect()

	defer browser.MustClose()
	
	page := browser.MustPage(g.blank()).MustWaitLoad()
	
	// ScreenCastRecord listen PageScreenCastFrame and convert it directly into AVI Movie
	_, errorRecord := page.ScreenCastRecord("sample.avi", 6) // Only support .avi video file & frame per second
	
	if errorRecord != nil {
		return errorRecord
	}
	// ScreenCastStart start listening ScreenCastRecord
	_, errorStart := page.ScreenCastStart(100, 1) // Image quality & frame per second
	
	if errorStart != nil {
		return errorStart
	}
	
	errorNavigate := page.Navigate("https://google.com")
	
	if errorNavigate != nil {
		return errorNavigate
	}
	
	time.Sleep(3 * time.Second)
	
	// ScreenCastStop stop listening ScreenCastRecord
	_, errorStop := page.ScreenCastStop()
	
	if errorStop != nil {
		return errorStop
	}
	
	page.MustClose()	
}
```

### CODE REVIEW

**Comment by alexferrari88** [comment]
do you need any help moving this forward?

**Comment by ysmood** [comment]
It will be great if you can pick it up. We also need to add ffmpeg to the rod docker image.

**Comment by alexferrari88** [comment]
sounds good, I will have a look as I have some time

**Comment by ysmood** [comment]
I renamed the master branch to main, the master branch doesn't exist anymore, Github will auto close PR for non-exist branch.

Sorry for the inconvenient, could you please remake a PR and link it to this old one?

**Pull request closed without merging**
