### PR TITLE
Add NoSandbox function

### LINKED ISSUE #368: Add function NoSandbox
Some Linux/Chrome version combinations make the browser throw "running as root without --no-sandbox is not supported" error. See https://crbug.com/638180.

### PR DESCRIPTION
**Pull request by aurkenb**
Fix #368 

Added NoSandbox(bool) function to easily switch mode.

### CODE REVIEW

**Review by ysmood — CHANGES_REQUESTED** [review]
Please read this https://github.com/go-rod/rod/blob/master/.github/CONTRIBUTING.md#code-coverage

**Comment by aurkenb** [comment]
> Please read this https://github.com/go-rod/rod/blob/master/.github/CONTRIBUTING.md#code-coverage

Already did :)

Coverage 100%

**Comment by ysmood** [comment]
Read the CI:
image

**Comment by aurkenb** [comment]
> Read the CI:
> image

Oops! My bad. 
Done :)

**Comment by aurkenb** [comment]
Oops! My bad.
Done :)

**Review by ysmood — APPROVED** [review]

**Pull request merged**
