### PR TITLE
hijack once

### PR DESCRIPTION
**Pull request by kvii**
# Development guide

[Link](https://github.com/go-rod/rod/blob/master/.github/CONTRIBUTING.md)

## Test on local before making the PR

```bash
go run ./lib/utils/simple-check
```

new PR for #696.

### CODE REVIEW

**Comment by ysmood** [comment]
I have updated the linter, please fix the lint error in CI.

**Comment by kvii** [comment]
It will FAIL when I call `go test -timeout 15s github.com/go-rod/rod` multiple.

``` txt
go test -timeout 15s github.com/go-rod/rod
ok  	github.com/go-rod/rod	9.284s

go test -timeout 15s github.com/go-rod/rod
parallel test 10
panic: test timed out after 15s

goroutine 1428 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2036 +0x88
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x38

goroutine 1 [chan receive]:
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1412 +0x44c
testing.tRunner(0x14000149040, 0x1400016bc28)
	/usr/local/go/src/testing/testing.go:1452 +0x148
testing.runTests(0x140001b4b40?, {0x104d9dd00, 0xd1, 0xd1}, {0x14000108060?, 0x1400002e6c0?, 0x104da1e20?})
	/usr/local/go/src/testing/testing.go:1844 +0x3f0
testing.(*M).Run(0x140001b4b40)
	/usr/local/go/src/testing/testing.go:1726 +0x4f0
github.com/go-rod/rod_test.TestMain(0x14000066ec8?)
	/Users/kvii/workspace/kvii/rod/setup_test.go:46 +0x64
main.main()
	_testmain.go:485 +0x1d4
...
```

But It will not FAIL when I annotate these code .

``` go
func TestHijackOnceSetError(t *testing.T) {
	g := setup(t)

	p, cancel := g.page.WithCancel()
	cancel()

	once := p.HijackOnce()
	err := once.Set("", "")

	g.Err(err)
}

func TestHijackOnceSetPattern(t *testing.T) {
	g := setup(t)

	p, cancel := g.page.WithCancel()
	cancel()

	once := p.HijackOnce()
	err := once.SetPattern(&proto.FetchRequestPattern{})

	g.Err(err)
}
```

I don't know hot to solve this problem.

**Comment by ysmood** [comment]
Because all test cases share the same `g.page`, if you are leaking something all other tests use `g.page` will be affected.

**Comment by kvii** [comment]
> Because all test cases share the `g.page` pool, if you are leaking something all other tests that use `g.page` will be affected.

I executed `go test`, a shell command twice.
Is there anything that can be shared between two shell commands?
If so,what leaked from the above code?

**Comment by ysmood** [comment]
> Is there anything that can be shared between two shell commands?

No, nothing will be shared between two `go test`, but `g.page` may be shared between two test cases, one `go test` will run hundreds of test cases.

**Comment by kvii** [comment]
Maybe go cached something between two `go test`.
So can I understand that as long as the first test passes, it will be fine?

**Comment by ysmood** [comment]
Because golang runs tests concurrently with random order. Sometimes, even if your test leaks state, it may work fine because it may run your leak test at the end.

**Comment by ysmood** [comment]
If you read your code carefully:

```go
func TestHijackOnceSetError(t *testing.T) {
	g := setup(t)

	p, cancel := g.page.WithCancel()
	cancel()

	once := p.HijackOnce()
	err := once.Set("", "")

	g.Err(err)
}
```

It is apparently leaking the `Fetch` config to other tests.

**Comment by kvii** [comment]
The context of p is already done.
So `proto.FetchEnable` will return an error of `"context canceled"`.
Will  `proto.FetchEnable.Call` still be issued even if the context has done?

**Comment by ysmood** [comment]
I see, looks like something else that is leaking.

**Comment by kvii** [comment]
Should we check if ctx has been done before the request will be sent? #704

**Review by ysmood — CHANGES_REQUESTED** [review]

**Comment by kvii** [comment]
Note the bug of context is still exits.
As we discussed in #704, we don't know if the request is actually sent when the context is done.

**Comment by ysmood** [comment]
Got it, I will take some time to debug your code.

**Comment by ysmood** [comment]
I renamed the master branch to main, the master branch doesn't exist anymore, Github will auto close PR for non-exist branch.

Sorry for the inconvenient, could you please remake a PR and link it to this old one?

**Comment by kvii** [comment]
Sorry, I can't make a new PR.
The main reasons are following:
1. I have no idea to solve the context-leak bug.
2. There are no requirements that need rod in my company.

**Pull request closed without merging**
