### PR TITLE
fix ScreentshotFullPage method

### PR DESCRIPTION
**Pull request by yasarluo**
Fix ScreenshotFullPage method can not save file error.

### CODE REVIEW

**Comment by yasarluo** [comment]
There is already a TestScreenshotFullPage method.

**Comment by ysmood** [comment]
I mean test if the output file exists.

**Comment by ysmood** [comment]
Test like this:

https://github.com/go-rod/rod/blob/539ae1df4e922514557dcf86adcf0c1b052ef17d/page_test.go#L394-L396

**Comment by ysmood** [comment]
@youshy Seems like a bug of your code

**Comment by yasarluo** [comment]
done

**Comment by ysmood** [comment]
Nice catch, thank you every much!

**Comment by ysmood** [comment]
Your change is on v0.46.6

**Pull request merged**
