### PR TITLE
fix unpack params with asasalint

### PR DESCRIPTION
**Pull request by alingse**
# Development guide

[Link](https://github.com/go-rod/rod/blob/master/.github/CONTRIBUTING.md)

## Test on local before making the PR

```bash
go run ./lib/utils/simple-check
```

## How

I create a [linter](https://github.com/alingse/asasalint) about pass []any as any into  variadic function

the linter output

```
.../github/rod/must.go:870:24: pass []any as any to func Eval func(js string, args ...interface{}) *github.com/go-rod/rod.EvalOptions
```

### CODE REVIEW

**Comment by alingse** [comment]
I have run lint on my local, only two failed with  `context.deadlineExceededError`
```
[launcher.Browser]2022/07/06 00:50:06 100%
--- FAIL: TestManaged (29.84s)
    private_test.go:117: 
        ⦗last argument⦘
        
        context.deadlineExceededError{
        }
        
        ⦗should be⦘
        
        nil
FAIL
coverage: 96.3% of statements
```

**Comment by ysmood** [comment]
Sorry, I accidentally merged your commit, now I reverted it, please read the source code of `Page.Wait`, it uses Eval already:

https://github.com/go-rod/rod/blob/c7dfaa5134f07ae89fc7176e9fdfccb3f1d5dd56/page.go#L595

**Comment by ysmood** [comment]
If you still want to do something, please create a unit test that can prove your idea.

**Comment by alingse** [comment]
what I changed is only the element MustWait
截屏2022-07-06 上午8 50 17

and Eval Signature
```golang
func Eval(js string, args ...interface{}) *EvalOptions 
```

how Eval used in rod repo was list here.

```golang
func (el *Element) MustEval(js string, params ...interface{}) gson.JSON {
	res, err := el.Eval(js, params...)
	el.e(err)
	return res.Value
}
---------------
func (el *Element) MustElementByJS(js string, params ...interface{}) *Element {
	el, err := el.ElementByJS(Eval(js, params...))
	el.e(err)
	return el
}
---------------
func (p *Page) MustEval(js string, params ...interface{}) gson.JSON {
	res, err := p.Eval(js, params...)
	p.e(err)
	return res.Value
}
---------------
func (p *Page) MustWait(js string, params ...interface{}) *Page {
	p.e(p.Wait(nil, js, params))
	return p
}
---------------
func (p *Page) Wait(this *proto.RuntimeRemoteObject, js string, params []interface{}) error {
	return utils.Retry(p.ctx, p.sleeper(), func() (bool, error) {
		opts := Eval(js, params...).ByPromise().This(this)
---------------

func (el *Element) CanvasToImage(format string, quality float64) ([]byte, error) {
	res, err := el.Eval(`(format, quality) => this.toDataURL(format, quality)`, format, quality)

---------------
fmt.Println("1 + 2 =", page.MustEval(`(a, b) => a + b`, 1, 2).Int())
---------------
func (p *Page) WaitElementsMoreThan(selector string, num int) error {
	return p.Wait(nil, `(s, n) => document.querySelectorAll(s).length > n`, []interface{}{selector, num})
}
```

the common usage by Eval is that `Eval(js, params....interface{})` , and you can see 
`Element.MustEval` and `Element.MustWait` and `Page.MustEval`

the only different is `Page.Wait`, it should changed, (but worked now, because finally unpack params in func body

you can see the `WaitElementsMoreThan` pass  `[]interface{}{selector, num}` to `Page.Wait`, but finally, it change to `params...` for Eval


so, most case  `Eval` has no param or only one param, and the others need be unpacked


I think my change lines is ok. and I will add some unittest in another PR.

**Comment by ysmood** [comment]
Also, can you help to change the `Page.Wait` from:

```go
func (p *Page) Wait(this *proto.RuntimeRemoteObject, js string, params []interface{}) error
```

to:

```go
func (p *Page) Wait(opts *EvalOptions) error
```

**Comment by alingse** [comment]
ok, I will try, but need go to work now 😂

**Pull request merged**
