### PR TITLE
Add function IsNavigation.

### LINKED ISSUE #336: How to determine whether the request is a navigation request in HijackRequests？
How to determine whether the request is a navigation request in HijackRequests？

The function I want to achieve is:

**Intercept navigation request**: judge the request and intercept it while returning status 204, so that the browser can not only send out the request, but also prevent the page from jumping. But I didn't see the relevant judgment method in HijackRequest.

### PR DESCRIPTION
**Pull request by Threezh1**
Determine whether the request is a navigation request

Fix #336

Description for the changes.
Add function IsNavigation.

### CODE REVIEW

**Comment by ysmood** [comment]
Thank you for your contribution! Please fix the error of the GitHub Actions, if you have questions please read https://github.com/go-rod/rod/blob/master/.github/CONTRIBUTING.md

**Comment by aurkenb** [comment]
@Threezh1 Add git pull and add the corresponding test in hijack_test.go

t.Is(ctx.Request.IsNavigation(), false)
-- line 55

**Comment by aurkenb** [comment]
@Threezh1 Git pull and add the corresponding test in hijack_test.go

t.Is(ctx.Request.IsNavigation(), false)
-- line 55

**Comment by ysmood** [comment]
#383

**Pull request closed without merging**
