### PR TITLE
WaitElementsLessThan

### PR DESCRIPTION
**Pull request by abakum**
Related to #878

### CODE REVIEW

**Comment by ysmood** [comment]
Why do you need this, could you provide a simple use case?

**Comment by abakum** [comment]
When the server processes the request, the page shows dots rotating around the ring. To take a screenshot, you need to wait until they are gone. 
I do it like this:
```
	sel = "div.circle"
	WaitElementsLessThan(page.Timeout(to*3), sel, 1)
```

**Comment by abakum** [comment]
page.Timeout(to * 3).MustElement(sel).WaitInvisible()
do not help

**Comment by ysmood** [comment]
How about using:

```go
page.MustElement(`div.circle`).Timeout(3 * time.Second).WaitInvisible()
```

**Comment by abakum** [comment]
Sometimes the request is fast and `div.circle` doesn't show up then WaitInvisible hang.
This work:
```
	if page.MustHas(sel) {
		page.Timeout(to * 3).MustElement(sel).WaitInvisible()
	}

```
but 
```
page.Timeout(to*3).MustWaitElementsLessThan(sel, 1)
```
IMHO more convenient

**Comment by Fly-Playgroud** [comment]
> When the server processes the request, the page shows dots rotating around the ring. To take a screenshot, you need to wait until they are gone. I do it like this:
> 
> ```
> 	sel = "div.circle"
> 	WaitElementsLessThan(page.Timeout(to*3), sel, 1)
> ```

I think you need [`Page.WaitStable`](https://github.com/go-rod/rod/blob/92a6a5078e54b3dacd92c19c5e517a799d381824/page.go#LL617C16-L617C26),
you could try this.

**Comment by abakum** [comment]
Don't ask for rain — ask for harvest!

**Comment by Fly-Playgroud** [comment]
> Don't ask for rain — ask for harvest!

If you think `Page.WaitStable` solve your issue. We will close this pr.

**Pull request closed without merging**
