### PR TITLE
Allow regex flags in ElementR

### LINKED ISSUE #315: Let the Page.ElementR support regex flags
Such as the case-insensitive flag.

### PR DESCRIPTION
**Pull request by infinitepr0**
Closes #315

### CODE REVIEW

**Comment by infinitepr0** [comment]
@ysmood Can you please investigate why `go generate` is trying to undo the commit changes (to the javascript code, not tests)?

**Comment by ysmood** [comment]
Read the first line of helper.go file 😂

**Comment by infinitepr0** [comment]
> Read the first line of helper.go file

Haha, I guess I still have lots to learn (reading comments at the top of code files being one of them :p)

**Review by ysmood — APPROVED** [review]
God job!

**Pull request merged**
