### PR TITLE
fix： #505

### LINKED ISSUE #505: panic!
**Rod Version:** v0.101.8

## The code to demonstrate your question

```go
wait := p.Browser().Timeout(5 * time.Second).WaitDownload("./")
p.Navigate(fileUrl)
bt := wait() // this line is panic line
```

## What have you tried to solve the question

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6f9efb]

goroutine 229 [running]:
github.com/go-rod/rod.(*Browser).WaitDownload.func2(0x1)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/browser.go:502 +0x1b
reflect.Value.call({0x7948a0, 0xc0000d1f60, 0x100c00015bb50}, {0x848677, 0x4}, {0xc00015bc68, 0x1, 0xc000119770})
	/usr/local/go/src/reflect/value.go:543 +0x814
reflect.Value.Call({0x7948a0, 0xc0000d1f60, 0xc000119770}, {0xc00015bc68, 0x1, 0x1})
	/usr/local/go/src/reflect/value.go:339 +0xc5
github.com/go-rod/rod.(*Browser).eachEvent.func1()
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/browser.go:397 +0x405
github.com/go-rod/rod.(*Browser).WaitDownload.func3()
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/browser.go:517 +0x91
main.loadImage.func1({0xc0000d9b10, 0xc0000d1ba0})

### PR DESCRIPTION
**Pull request by mlboy**
fix #505 

# Development guide

[Link](https://github.com/go-rod/rod/blob/master/.github/CONTRIBUTING.md)

## Test on local before making the PR

```bash
go run ./lib/utils/simple-check
```

### CODE REVIEW

**Comment by ysmood** [comment]
Good job! Please run `go run ./lib/utils/simple-check` on your local and fix the errors.

**Comment by mlboy** [comment]
when I run simple-check and got this result,  It is not fair to me
```
go test -coverprofile=coverage.out
parallel test 4
--- FAIL: Test (0.01s)
    --- FAIL: Test/ScreenshotFullPage (3.39s)
        page_test.go:580: 2061 ⦗not ==⦘ 4122

            1   - 2061
              1 + 4122

        page_test.go:581: 1537 ⦗not ==⦘ 3075

            1   - 1537
              1 + 3075

    --- FAIL: Test/EmulateDevice (0.45s)
        page_test.go:222: 1743 ⦗not ==⦘ 1742

            1   - 1743
              1 + 1742

    --- FAIL: Test/BrowserPages (1.75s)
        browser_test.go:83:  ⦗expect len⦘ 4 ⦗to be⦘ 3
        browser_test.go:91:  ⦗expect len⦘ 3 ⦗to be⦘ 2
FAIL
coverage: 100.0% of statements
exit status 1
FAIL	github.com/go-rod/rod	17.979s
panic: exit status 1
```

**Comment by ysmood** [comment]
How about using the docker image to run the test: https://github.com/go-rod/rod/blob/master/lib/examples/launch-managed/main.go

**Comment by mlboy** [comment]
i added unit test.

**Review by ysmood — DISMISSED** [review]

**Comment by mlboy** [comment]
On my local, I just got this error, but in actions test?

local：
```
(base) ➜  rod git:(fix-issues-505) go test -race ./...
parallel test 4
--- FAIL: Test (0.06s)
    --- FAIL: Test/EmulateDevice (0.25s)
        page_test.go:222: 1743 ⦗not ==⦘ 1742

            1   - 1743
              1 + 1742

    --- FAIL: Test/BrowserPages (0.54s)
        browser_test.go:83:  ⦗expect len⦘ 4 ⦗to be⦘ 3
        browser_test.go:91:  ⦗expect len⦘ 3 ⦗to be⦘ 2
    --- FAIL: Test/ScreenshotFullPage (23.21s)
        page_test.go:580: 2061 ⦗not ==⦘ 4122

            1   - 2061
              1 + 4122

        page_test.go:581: 1537 ⦗not ==⦘ 3075

            1   - 1537
              1 + 3075

FAIL
FAIL	github.com/go-rod/rod	34.788s
?   	github.com/go-rod/rod/fixtures/gen-fonts	[no test files]
?   	github.com/go-rod/rod/lib/assets	[no test files]
?   	github.com/go-rod/rod/lib/assets/generate	[no test files]
ok  	github.com/go-rod/rod/lib/cdp	(cached)
ok  	github.com/go-rod/rod/lib/defaults	(cached)
ok  	github.com/go-rod/rod/lib/devices	(cached)
?   	github.com/go-rod/rod/lib/devices/generate	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/click	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/cookie	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/emulate	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/eval	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/headers	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/keys	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/logic	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/remote	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/screenshot	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/submit	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/text	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/upload	[no test files]
?   	github.com/go-rod/rod/lib/examples/compare-chromedp/visible	[no test files]
?   	github.com/go-rod/rod/lib/examples/connect-browser	[no test files]
?   	github.com/go-rod/rod/lib/examples/custom-launch	[no test files]
?   	github.com/go-rod/rod/lib/examples/debug-deadlock	[no test files]
?   	github.com/go-rod/rod/lib/examples/disable-window-alert	[no test files]
?   	github.com/go-rod/rod/lib/examples/launch-managed	[no test files]
?   	github.com/go-rod/rod/lib/examples/stripe	[no test files]
?   	github.com/go-rod/rod/lib/examples/translator	[no test files]
?   	github.com/go-rod/rod/lib/examples/use-rod-like-chrome-extension	[no test files]
?   	github.com/go-rod/rod/lib/input	[no test files]
?   	github.com/go-rod/rod/lib/js	[no test files]
?   	github.com/go-rod/rod/lib/js/generate	[no test files]
ok  	github.com/go-rod/rod/lib/launcher	(cached)
?   	github.com/go-rod/rod/lib/launcher/flags	[no test files]
?   	github.com/go-rod/rod/lib/launcher/revision	[no test files]
?   	github.com/go-rod/rod/lib/launcher/rod-manager	[no test files]
ok  	github.com/go-rod/rod/lib/proto	(cached)
?   	github.com/go-rod/rod/lib/proto/generate	[no test files]
ok  	github.com/go-rod/rod/lib/utils	1.204s
?   	github.com/go-rod/rod/lib/utils/check-cov	[no test files]
?   	github.com/go-rod/rod/lib/utils/check-issue	[no test files]
?   	github.com/go-rod/rod/lib/utils/docker	[no test files]
?   	github.com/go-rod/rod/lib/utils/get-browser	[no test files]
?   	github.com/go-rod/rod/lib/utils/lint	[no test files]
?   	github.com/go-rod/rod/lib/utils/rename	[no test files]
?   	github.com/go-rod/rod/lib/utils/setup	[no test files]
?   	github.com/go-rod/rod/lib/utils/simple-check	[no test files]
FAIL
```

actions:
```
panic: Test/WaitDownloadFromNewPage timeout after 1m0s
```

**Pull request closed without merging**
