### PR TITLE
ensure that Response.Body-s have been closed

### PR DESCRIPTION
**Pull request by egonelbre**
Per https://golang.org/pkg/net/http/#Client.Get (and similar) the caller should always close `Response.Body`.

Updates #427

### CODE REVIEW

**Comment by egonelbre** [comment]
It looks like the test-suite started downloading Chrome 884014 for some reason. This is not in sync with what the codebase expects.

**Comment by ysmood** [comment]
> It looks like the test-suite started downloading Chrome 884014 for some reason. This is not in sync with what the codebase expects

No, we are intentionally doing the download to make sure the download gets tested.

**Comment by egonelbre** [comment]
I regenerated the proto things and it's now passing.

**Comment by ysmood** [comment]
> I regenerated the proto things and it's now passing.

You can remove this commit, I updated the master branch.

**Review by ysmood — APPROVED** [review]

**Pull request merged**
